[package]
name = "trendbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2pdf = "0.7.0"
reqwest = { version = "0.11.23", features = ["cookies"] }
scraper = "0.18.1"
serde = { version = "1.0.194", features = ["derive"] }
serenity = "0.12.0"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
